---
- name: Arch system prep.
  hosts: arch:children
  become: true

  tasks:
    - name: Install base packages
      community.general.pacman:
        name:
          - git
          - neofetch
          - neovim
          - tmux
          - glances
          - btop
          - htop
          - wget
          - curl
          - ufw
          - ansible
          - extra/jdk-openjdk
