---
- name: Upgrade everything, reboot if required.
  hosts: andromeda
  become: true
  gather_facts: no

  tasks:
    - name: Upgrade all software.
      pacman:
        update_cache: yes
        upgrade: yes
