---
- name: Upgrade everything, reboot if required.
  hosts: rpi-pihole
  become: false
  gather_facts: no

  tasks:
    - name: Running apt upgrade && apt update
      ansible.builtin.shell:
        cmd: sudo apt update && sudo apt upgrade -y
      async: 2100
      poll: 0
      register: apt_up

    - name: Check progress
      async_status:
        jid: "{{ apt_up.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      delay: 10
      retries: 300

    - name: Check if a reboot is required.
      stat:
        path: /var/run/reboot-required
        get_md5: no
      register: reboot_required_file

    #- name: Reboot the server (if required).
    #  reboot:
    #when: reboot_required_file.stat.exists == true
