---
- name: Update pihole
  hosts: rpi-pihole
  become: false
  gather_facts: no

  tasks:
    - name: Running pihole -up
      ansible.builtin.shell:
        cmd: pihole -up
      async: 2100
      poll: 0
      register: pihole_up

    - name: Check progress
      async_status:
        jid: "{{ pihole_up.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      delay: 10
      retries: 300
