---
- name: Update apt, dist-upgrade, autoclean, & autoremove everything, reboot if required.
  hosts: cluster:nodes
  become: true

  tasks:
    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
          - git
          - neovim
          - curl
          - wget
          - tmux
          - glances
          - htop
          - btop

      async: 2100
      poll: 0
      register: pkg_install

    - name: Run the equivalent of "apt-get clean" as a separate step
      apt:
        clean: yes

    - name: Running apt upgrade && apt update
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        autoclean: yes
        autoremove: yes

      # ansible.builtin.shell:
      # cmd: sudo apt update && sudo apt upgrade -y
      async: 2100
      poll: 0
      register: apt_up

    - name: Check progress
      async_status:
        jid: "{{ apt_up.ansible_job_id }}"
        jid: "{{ pkg_install.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      delay: 10
      retries: 300

    #- name: Remove useless packages from the cache
    #  ansible.builtin.apt:
    #  autoclean: yes

    # - name: Remove dependencies that are no longer required
    #  ansible.builtin.apt:
    # autoremove: yes

    - name: Check if a reboot is required.
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot the server (if required).
      reboot:
      when: reboot_required_file.stat.exists == true
